name: PHP lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ["5.4", "8.1"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check for syntax errors
      run: |
        git diff --diff-filter=d --name-only HEAD^ | grep '\.php$' | xargs -rn 1 php -l
